### ISSUE TITLE
Getting rid of the web.xml

### ISSUE THREAD

**Issue by ihsancingisiz** [arey/spring-javaconfig-sample#1]
[DELETED]

**Comment by arey** [comment]
Hi Ihsan,
There is still a web.xml configuration file because this sample support the Servlet 2.5 API. WebApplicationInitializer requires Servlet 3.0+.
You can check the https://github.com/arey/spring-mvc-toolkit/blob/master/spring-mvc-toolkit-demo/src/main/java/com/javaetmoi/core/mvc/demo/init/DemoAppInitializer.java for an example of full Java configuration.
 Regards
